QuestionApp/Controllers/ClassesController.cs
using Microsoft.Ajax.Utilities;
using QuestionApp.Models;
using QuestionApp.Models.Addon;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
namespace QuestionApp.Controllers
{
    public class ClassesController : Controller
    {
        private DBContext db = new DBContext();
        [HttpGet]
        public ActionResult StudentResult(int LibraryID, int? ClassID)
        {
            TempData["class"] = ClassID;
            return View(db.Answers.Where(x => x.LibraryID == LibraryID && x.ClassID == ClassID && x.Status == "0").ToList());
        }
        // GET: Classes
        public ActionResult Index()
        {
            return View(db.Class.ToList());
        }
        // GET: Classes/Details/5
        public ActionResult Result(int? QuizID,int? StudentID)
        {
            var FindLib = db.QuizLibrary.Find(QuizID);
            TempData["QuizID"] = FindLib.ID;
            TempData["StudentID"] = StudentID;
            var FindStudent = db.Students.Find(StudentID);
            var FindResult = db.Answers.Where(x => x.LibraryID == FindLib.ID && x.StudentID == FindStudent.ID).ToList();
            return View(FindResult);
        
        }
        [HttpPost]
        public ActionResult Result(int? QuizID, int? StudentID,int Answer,string Dogru, int ss)
        {
            var FindLib = db.QuizLibrary.Find(QuizID);
            TempData["QuizID"] = FindLib.ID;
            TempData["StudentID"] = StudentID;
            var FindStudent = db.Students.Find(StudentID);
            var FindResult = db.Answers.Where(x => x.LibraryID == FindLib.ID && x.StudentID == FindStudent.ID).ToList();
            if (Dogru!=null)
            {
                var ExamResultChange = db.Answers.Find(ss);
                ExamResultChange.Pass = true;
                ExamResultChange.TotalPoint = 1;
                db.SaveChanges();
            }
            else
            {
                var ExamResultChange = db.Answers.Find(ss);
                ExamResultChange.Pass = false;
                ExamResultChange.TotalPoint = 1;
                db.SaveChanges();
            }
           
            
            return View(FindResult);

        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Class.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }
        // GET: Classes/Create
        public ActionResult Create()
        {
            ViewBag.kutuphane = db.QuizLibrary.ToList();
            ViewBag.ogrenic = db.Students.ToList();
            return View();
        }
        // POST: Classes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string Name, string QuizLib, string[] Student, string[] Library, Class @class)
        {
            if (ModelState.IsValid)
            {
                var Exist = db.Class.FirstOrDefault(x => x.Name == Name);
                if (Exist == null)
                {
                    @class.Name = Name;
                    @class.QuizLib = QuizLib;
                    @class.Students = string.Join("|", Student);
                    @class.QuizLib = string.Join("|", Library);
                    @class.CratedDate = DateTime.Now.ToString();
                    db.Class.Add(@class);
                    db.SaveChanges();
                    MailSender.MailGonder(@class.ID);
                    Logger.LogKeeper(Name + " Sınıfı oluşturdu ve mail gönderildi");
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["exist"] = true;
                    return View(@class);
                }
            }
            return View();
        }
        // GET: Classes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Class.Find(id);
            ViewBag.kutuphane = db.QuizLibrary.ToList();
            ViewBag.ogrenic = db.Students.ToList();
            if (!string.IsNullOrEmpty(@class.Students))
            {
                @class.Student = @class.Students.Split('|').ToArray();
            }
            if (!string.IsNullOrEmpty(@class.QuizLib))
            {
                @class.Library = @class.QuizLib.Split('|').ToArray();
            }
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }
        // POST: Classes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Students,QuizLib,CratedDate")] Class @class, string[] Student, string[] Library)
        {
            if (ModelState.IsValid)
            {
                if (Student == null)
                {
                    @class.Students = null;
                }
                else
                {
                    @class.Students = string.Join("|", Student);
                }
                if (Library == null)
                {
                    @class.QuizLib = null;
                }
                else
                {
                    @class.QuizLib = string.Join("|", Library);
                }
                db.Entry(@class).State = EntityState.Modified;
                db.SaveChanges();
                MailSender.MailGonder(@class.ID);
                return RedirectToAction("Index");
            }
            return View(@class);
        }
        // GET: Classes/Delete/5
        // POST: Classes/Delete/5
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Class @class = db.Class.Find(id);
            db.Class.Remove(@class);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuestionApp/Views/Classes/Create.cshtml
@model QuestionApp.Models.Class
@{
    ViewBag.Title = "From list";
}
@using (Html.BeginForm("Create", "Classes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12 col-xlg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.QuizLib, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.ListBoxFor(model => model.QuizLib, new SelectList(ViewBag.kutuphane, "ID", "Name"), new { @class = "form-control", @id = "ss" })
                            @Html.ValidationMessageFor(model => model.QuizLib, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Students, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.ListBoxFor(model => model.Student, new SelectList(ViewBag.ogrenic, "ID", "NickName"), new { @class = "form-control", @id = "kulls" })
                            @Html.ValidationMessageFor(model => model.Students, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn btn-outline-primary" name="Kaydet" value="Ekle" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<link href="~/Content/toastr.min.css" rel="stylesheet" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/toastr.min.js"></script>
    <link href="~/Content/multi-select.css" rel="stylesheet" />
    <script src="~/Content/jquery.multi-select.js"></script>
    <script src="~/Scripts/Searchq.js"></script>
    <script type="text/javascript">
        // run pre selected options
        $('#kulls').multiSelect({
            selectableHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Kullanıcı ara'>",
            selectionHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Seçilmiş olanı ara'>",
            afterInit: function (ms) {
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';
                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                    .on('keydown', function (e) {
                        if (e.which === 40) {
                            that.$selectableUl.focus();
                            return false;
                        }
                    });
                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                    .on('keydown', function (e) {
                        if (e.which == 40) {
                            that.$selectionUl.focus();
                            return false;
                        }
                    });
            },
            afterSelect: function () {
                this.qs1.cache();
                this.qs2.cache();
            },
            afterDeselect: function () {
                this.qs1.cache();
                this.qs2.cache();
            }
        });
    </script>
    <script type="text/javascript">
        // run pre selected options
        $('#ss').multiSelect({
            selectableHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Kullanıcı ara'>",
            selectionHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Seçilmiş olanı ara'>",
            afterInit: function (ms) {
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';
                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                    .on('keydown', function (e) {
                        if (e.which === 40) {
                            that.$selectableUl.focus();
                            return false;
                        }
                    });
                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                    .on('keydown', function (e) {
                        if (e.which == 40) {
                            that.$selectionUl.focus();
                            return false;
                        }
                    });
            },
            afterSelect: function () {
                this.qs1.cache();
                this.qs2.cache();
            },
            afterDeselect: function () {
                this.qs1.cache();
                this.qs2.cache();
            }
        });
    </script>
    @if (TempData["hata"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["success"]("Kayıt Düzenlendi")
                toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
    @if (TempData["getir"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["success"]("Kayıt Getirildi")
                toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
}

QuestionApp/Views/Classes/Delete.cshtml
@model QuestionApp.Models.Class
@{
    ViewBag.Title = "Delete";
}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Class</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Students)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Students)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.QuizLib)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuizLib)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CratedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CratedDate)
        </dd>
    </dl>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuestionApp/Views/Classes/Details.cshtml
@model QuestionApp.Models.Class
@{
    ViewBag.Title = "Details";
}
<style>
    td {
        white-space: nowrap;
        overflow: hidden;
        -o-text-overflow: ellipsis;
        -ms-text-overflow: ellipsis;
        text-overflow: ellipsis;
        max-width: 200px;
    }
    input {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        width: 200px;
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }
    input {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        width: 200px;
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }
        input:focus {
            outline: none;
            border-color: #aaa
        }
    select {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }
    select {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }
        select:focus {
            outline: none;
            border-color: #aaa
        }
</style>
<div class="row">
    <div class="col-12 col-md-12">
        <div class="card">
            <div class="card-body">
                <p>
                    @Html.ActionLink("< Listeye Geri Dön", "Index")
                </p>
                <div>
                    <h4>@Html.DisplayFor(model => model.Name)</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.QuizLib)
                        </dt>
                        <dd>
                            @{
                                QuestionApp.Models.DBContext db = new QuestionApp.Models.DBContext();
                                if (Model.QuizLib != "" && Model.QuizLib != null)
                                {
                                    foreach (var item in Model.QuizLib.Split('|'))
                                    {
                                        if (item != null)
                                        {
                                            int i = Convert.ToInt32(item);
                                            var bul = db.QuizLibrary.FirstOrDefault(x => x.ID == i);
                                            <a href="~/Classes/StudentResult/@bul.ID/@Model.ID" target="_blank">@bul.Name</a>
                                            <br />
                                        }
                                    }
                                }
                            }
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.CratedDate)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.CratedDate)
                        </dd>
                    </dl>
                </div>
                @{
                    @Html.ActionLink("Düzenle", "Edit", new { id = Model.ID }, new { @class = "btn btn-outline-primary btn-md" })
                    <button type="button" class="btn btn-outline-danger btn float-right" data-toggle="modal" data-target="#exampleModal">
                        Sil
                    </button>
                    <p>
                        @Html.ActionLink("< Listeye Geri Dön", "Index")
                    </p>
                }
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Kaydı silmek istediğinize emin misiniz ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @Model.Name adlı Sınıfı silmek istediğinize emin misiniz ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hayır</button>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Evet" class="btn btn-danger" />
                }
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-12">
        <div class="card">
            <div class="card-body">
                <table id="datatable" class="table tables table-hover table-sm " style="width: 100%;" role="grid" aria-describedby="scroll_ver_dynamic_hei_info">
                    <thead>
                        <tr>
                            <th>
                                Öğrenci Adı
                            </th>
                            <th>
                                Aldığı Puan
                            </th>
                            <th>İncele</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (!string.IsNullOrEmpty(Model.Students))
                            {
                                foreach (var item in Model.Students.Split('|'))
                                {
                                    if (item != null)
                                    {
                                        int ID = Convert.ToInt32(item);
                                        int QuizID = Convert.ToInt32(Model.QuizLib);
                                        var bul = db.Students.FirstOrDefault(x => x.ID == ID);
                                        var PaunAl = db.Answers.FirstOrDefault(x => x.StudentID == ID && x.LibraryID == QuizID);
                                        <tr>
                                            <td>  <a href="~/StudentsOps/Details/@bul.ID" target="_blank">@bul.FirsName @bul.LastName</a></td>
                                            @if (PaunAl != null)
                                            {
                                                <td>@PaunAl.TotalPoint</td>
                                                <td>
                                                    @Html.ActionLink("Detaylar", "Result", "Classes", new { QuizID = QuizID, StudentID = bul.ID, Answer = PaunAl.ID },
    new { target = "_blank" })
                                                </td>
                                            }
                                            else
                                            {
                                                <td>0</td>
                                                <td></td>
                                            }
                                        </tr>
                                    }
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<link href="~/Content/toastr.min.css" rel="stylesheet" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    @Scripts.Render("~/bundles/Datatable")
    <script src="~/Scripts/toastr.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable({
                "language": {
                    "url": "/Scripts/Turkish.json"
                },
                "dom": ' <"search"f><"bottom"l>rt<"bottom"ip><"clear"><"top"B>',
                buttons: [
                    {
                        extend: 'excelHtml5',
                        exportOptions:
                        {
                            columns: [0, 1, 2],
                        },
                        text: '<i class="fa fa-file-excel-o"></i>',
                        titleAttr: 'Excel',
                        className: 'btn btn-outline-secondary'
                    },
                    {
                        extend: 'pdfHtml5',
                        pageSize: 'LEGAL',
                        exportOptions:
                        {
                            columns: [0, 1, 2],
                        },
                        text: '<i class="fa fa-file-pdf-o"></i>',
                        titleAttr: 'PDF',
                        className: 'btn btn-outline-secondary'
                    },
                    {
                        text: '<b>Sınıf Oluştur</b>',
                        action: function (e, dt, button, config) {
                            window.location = '/Classes/Create';
                        },
                        className: 'btn btn-outline-info'
                    },
                ]
            });
        });
    </script>
    @if (TempData["Message"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["success"]("Kayıt Silindi", "Kayıt Silindi")
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
}