QuestionApp/Models/Question.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace QuestionApp.Models
{
    public class Question
    {
        [Key]
        public int QuestionID { get; set; }
        [DataType(DataType.Text)]
        [DisplayName("Soru Adı")]
        public string Name { get; set; }
        [DataType(DataType.Text)]
        [DisplayName("Soru")]
        public string Question { get; set; }
        [DataType(DataType.Text)]
        [DisplayName("Cevap")]
        public string Answers { get; set; }
        [DataType(DataType.Text)]
        [DisplayName("Açıklama")]
        public string Explanation { get; set; }
        [DataType(DataType.Text)]
        [DisplayName("Soru Tipi")]
        public string Type { get; set; }
        [DataType(DataType.Text)]
        [DisplayName("Oluşturulma Tarihi")]
        public DateTime CratedDate { get; set; }
        private DateTime Ekle()
        {
            return DateTime.Now;
        }
        public string True_Answers { get; set; }

    }
}

QuestionApp/Controllers/QuestionController.cs
using QuestionApp.Models;
using QuestionApp.Models.Addon;
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
namespace QuestionApp.Controllers
{
    public class QuestionController : Controller
    {
        private DBContext db = new DBContext();
        // GET: Question
        [HttpGet]
        [Compress]
        public ActionResult Index()
        {
            try
            {
                return View(db.Question.ToList());
            }
            catch (Exception e)
            {
                Errorer.ErrorKeeper(e.ToString());
                TempData["Error"] = "error";
                return View();
            }
        }
        [Compress]
        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                Errorer.ErrorKeeper(e.ToString());
                TempData["Error"] = "error";
                return View();
            }
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        [Compress]
        public ActionResult Create(Question asking, string QuestionName, string[] fields, string answers, string multiple, string MultipleQuestion, string Multipleexp, string truefalse, string trueQuestion, string options, string trueexp, string shoranswers, string shortQuestion, string shortAnswer, string shortExplan, string File, string FileQuestion, HttpPostedFileBase FileUpload, string paragraph, string Parag)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (multiple != null)
                    {
                        string ekel = string.Join("|", fields);
                        asking.Name = QuestionName;
                        asking.answers1 = answers;
                        asking.Type = "multiple";
                        asking.Questions = MultipleQuestion;
                        asking.Explanation = Multipleexp;
                        asking.Answers = ekel;
                        db.Question.Add(asking);
                        db.SaveChanges();
                    }
                    if (truefalse != null)
                    {
                        asking.Type = "truefalse";
                        asking.Name = QuestionName;
                        asking.Questions = trueQuestion;
                        asking.Explanation = trueexp;
                        asking.Answers = options;
                        db.Question.Add(asking);
                        db.SaveChanges();
                    }
                    if (shoranswers != null)
                    {
                        asking.Type = "short";
                        asking.Name = QuestionName;
                        asking.Questions = shortQuestion;
                        asking.Explanation = shortExplan;
                        asking.Answers = shortAnswer;
                        db.Question.Add(asking);
                        db.SaveChanges();
                    }
                    if (File != null)
                    {
                        asking.Type = "File";
                        asking.Name = "";
                        asking.Questions = FileQuestion;
                        asking.Explanation = "";
                        string files = DateTime.Now.ToShortDateString() + FileUpload.FileName;
                        var path = Path.Combine(Server.MapPath("~/Document"), files);
                        FileUpload.SaveAs(path);
                        asking.Answers = files;
                        db.Question.Add(asking);
                        db.SaveChanges();
                    }
                    if (Parag != null)
                    {
                        asking.Type = "Paragraph";
                        asking.Name = "";
                        asking.Questions = paragraph;
                        asking.Explanation = "";
                        asking.Answers = "";
                        db.Question.Add(asking);
                        db.SaveChanges();
                    }
                    Logger.LogKeeper("Soru Ekledi");
                    return Redirect("/Question/details/" + asking.ID);
                }
            }
            catch (Exception e)
            {
                Errorer.ErrorKeeper(e.ToString());
                TempData["Error"] = "error";
                return View(asking);
            }
            return View(asking);
        }
        [Compress]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question asking = db.Question.Find(id);
            if (asking.Type == "multiple")
            {
                string[] da = asking.Answers.Split('|').ToArray();
                ViewBag.da = da.ToList();
            }
            if (asking.Type == "short")
            {
                string[] shotrs = asking.Answers.Split(',').ToArray();
                ViewBag.shorta = shotrs.ToList();
            }
            if (asking == null)
            {
                return HttpNotFound();
            }
            return View(asking);
        }
        [Compress]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Question asking = db.Question.Find(id);
                if (asking == null)
                {
                    return HttpNotFound();
                }
                return View(asking);
            }
            catch (Exception e)
            {
                Errorer.ErrorKeeper(e.ToString());
                TempData["Error"] = "error";
                return View(db.Question.Find(id));
            }

        }
        // POST: Askings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Compress]
        public ActionResult Edit([Bind(Include = "ID,Type,Question,Answers,Explanation")] Question asking)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(asking).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(asking);
            }
            catch (Exception e)
            {
                Errorer.ErrorKeeper(e.ToString());
                TempData["Error"] = "error";
                return RedirectToAction("Index");
            }

        }
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        [Compress]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Question asking = db.Question.Find(id);
                db.Question.Remove(asking);
                db.SaveChanges();
                TempData["MessageMessage"] = "error";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Errorer.ErrorKeeper(e.ToString());
                TempData["Error"] = "error";
                return RedirectToAction("Index");
            }
        }
    }
}

QuestionApp/Views/Question/Create.cshtml
@{
    ViewBag.Title = "Soru Oluştur";
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div style="margin-bottom:15px">
                    @Html.ActionLink("< Listeye Geri Dön", "Index")
                </div>
                <ul class="nav nav-tabs customtab" role="tablist">
                    <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#multiple" role="tab"><span class="hidden-sm-up"><i class="fa fa-info"></i></span> <span class="hidden-xs-down">Çoktan Seçmeli</span></a> </li>
                    <li class="nav-item"> <a class="nav-link " data-toggle="tab" href="#truefalses" role="tab"><span class="hidden-sm-up"><i class="fa fa-barcode"></i></span> <span class="hidden-xs-down">Doğru Yanlış</span></a> </li>
                    <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#short" role="tab"><span class="hidden-sm-up"><i class="fa fa-ethernet"></i></span> <span class="hidden-xs-down">Kısa Cevaplar</span></a> </li>
                    <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#paragraf" role="tab"><span class="hidden-sm-up"><i class="fa fa-ethernet"></i></span> <span class="hidden-xs-down">Paragraf Soruları</span></a> </li>
                    <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#file" role="tab"><span class="hidden-sm-up"><i class="fa fa-ethernet"></i></span> <span class="hidden-xs-down">Dosya Yükle</span></a> </li>
                </ul>
                @using (Html.BeginForm("Create", "Question", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="tab-content">
                        <div class="tab-pane active" id="multiple" role="tabpanel">
                            <div class="p-20">
                                <div class="form-horizontal">
                                    <div class="form-group">
                                        <label class="control-label">Soru</label>
                                        <div class="col-md-12">
                                            <textarea name="MultipleQuestion" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="ourField">Cevap</label>
                                        <div id="myRepeatingFields">
                                            <div class="entry input-group col-xs-3">
                                                <input class="form-control" name="fields" type="text" placeholder="Cevap Giriniz" style="margin-bottom:20px" />
                                                <span class="input-group-btn">
                                                    <button type="button" class="btn btn-success btn-sm btn-add">
                                                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                                    </button>
                                                </span>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Doğru Cevabı Yazınız</label>
                                        <div class="col-md-12">
                                            <input type="text" name="answers" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Açıklama</label>
                                        <div class="col-md-12">
                                            <textarea name="Multipleexp" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <input type="submit" value="Oluştur" name="multiple" class="btn btn-outline-primary " />
                                    <br>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="truefalses" role="tabpanel">
                            <div class="form-horizontal">
                                <div class="p-20">
                                    <div class="form-group">
                                        <label class="control-label">Soru</label>
                                        <div class="col-md-12">
                                            <textarea name="trueQuestion" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Doğru/Yanlış</label>  <div class="col-md-12">
                                            <label class="btn btn-secondary active">
                                                <input type="radio" name="options" id="true" value="true" class="btn-outline-primary" autocomplete="off" checked> Doğru
                                            </label>
                                            <label class="btn btn-secondary">
                                                <input type="radio" name="options" id="false" value="false" class="btn-outline-danger" autocomplete="off"> Yanlış
                                            </label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Açıklama</label>
                                        <div class="col-md-12">
                                            <textarea name="trueexp" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <input type="submit" value="Oluştur" name="truefalse" class="btn btn-outline-primary " />
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane " id="short" role="tabpanel">
                            <div class="p-20">
                                <div class="form-horizontal">
                                    <div class="form-group">
                                        <label class="control-label">Soru</label>
                                        <div class="col-md-12">
                                            <textarea name="shortQuestion" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Cevap</label>
                                        <div class="col-md-12">
                                            <textarea name="shortAnswer" class="form-control"></textarea>
                                        </div>
                                        <small>Lütfen Cevapları ','(virgül) ile ayırınız</small>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Açıklama</label>
                                        <div class="col-md-12">
                                            <textarea name="shortExplan" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <input type="submit" value="Oluştur" name="shoranswers" class="btn btn-outline-primary " />
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="paragraf" role="tabpanel">
                            <div class="p-20">
                                <div class="form-horizontal">
                                    <div class="form-group">
                                        <label class="control-label">Soru</label>
                                        <div class="col-md-12">
                                            <textarea name="paragraph" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <input type="submit" value="Oluştur" name="Parag" class="btn btn-outline-primary " />
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="file" role="tabpanel">
                            <div class="p-20">
                                <div class="form-horizontal">
                                    <div class="form-group">
                                        <label class="control-label">Soru</label>
                                        <div class="col-md-12">
                                            <textarea name="FileQuestion" class="form-control"></textarea>
                                        </div>
                                        <label class="control-label">Dosya Yükle</label>
                                        <div class="col-md-12">
                                            <input type="file" class="file" name="FileUpload" />
                                        </div>
                                    </div>
                                    <input type="submit" value="Oluştur" name="File" class="btn btn-outline-primary " />
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <div>
                    @Html.ActionLink("< Listeye Geri Dön", "Index")
                </div>
                @section Scripts {
                                <script src="~/Scripts/bootstrap.min.js"></script>
                    @Scripts.Render("~/bundles/jqueryval")
                    <script>
                        $(function () {
                            $(document).on('click', '.btn-add', function (e) {
                                e.preventDefault();
                                var controlForm = $('#myRepeatingFields:first'),
                                    currentEntry = $(this).parents('.entry:first'),
                                    newEntry = $(currentEntry.clone()).appendTo(controlForm);
                                newEntry.find('input').val('');
                                controlForm.find('.entry:not(:last) .btn-add')
                                    .removeClass('btn-add').addClass('btn-remove')
                                    .removeClass('btn-success').addClass('btn-danger')
                                    .html('');
                            }).on('click', '.btn-remove', function (e) {
                                e.preventDefault();
                                $(this).parents('.entry:first').remove();
                                return false;
                            });
                        });
                    </script>
                }
            </div>
        </div>
    </div>
</div>

QuestionApp/Views/Question/Details.cshtml
@model QuestionApp.Models.Question
@{
    ViewBag.Title = "Details";
}
@{
    char bg = 'A';
    int a = 0;
}
<div class="row">
    <div class="col-12 col-md-12">
        <div class="card">
            <div class="card-body">
                <p style="float:right">
                    @{
                    
                        <button type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                            Sil
                        </button>                  
                    }
                </p>
                @Html.ActionLink("< Listeye Geri Dön", "Index")
                <h2>@Model.Questions</h2>
                <hr />
                <div style="margin-left:25px">
                    @if (Model.Type == "multiple")
                    {
                        foreach (var item in ViewBag.da)
                        {
                            <h4>@bg)@item</h4>
                            bg++;
                        }
                        <br />
                        <h5><b>Doğru Cevap:</b>@Model.answers1</h5>
                    }
                    @if (Model.Type == "truefalse")
                    {
                        <h3>@Model.Answers</h3>
                    }
                    @if (Model.Type == "short")
                    {
                        <h3>Cevaplar</h3>
                        <div style="margin-left:25px">
                            @foreach (var item in ViewBag.shorta)
                            {
                                if (item != "")
                                {
                                    a++;
                                    <h4>@a)@item</h4>
                                }
                            }
                        </div>
                    }
                    @if (Model.Type == "File")
                    {
                        <label>İndir</label>
                        <a href="~/Document/@Model.Answers">@Model.Answers</a>
                    }
                </div>
                <br />
                <h5>Açıklama:@Model.Explanation</h5>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Kaydı silmek istediğinize emin misiniz ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @Model.Name adlı soruyu silmek istediğinize emin misiniz ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hayır</button>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Evet" class="btn btn-danger" />
                }
            </div>
        </div>
    </div>
</div>

QuestionApp/Views/Question/Edit.cshtml
@model QuestionApp.Models.Question
@{
    ViewBag.Title = "Edit";
}
<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @if (Model.Type=="multiple")
        {
        }
    </div>
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Questions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Questions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Questions, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Answers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answers, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Explanation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Explanation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Explanation, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.answers1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answers1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answers1, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>