QuestionApp/Controllers/LibraryController.cs
using QuestionApp.Models;
using QuestionApp.Models.Addon;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
namespace QuestionApp.Controllers
{
    public class LibraryController : Controller
    {
        private DBContext db = new DBContext();
        // GET: Library
        public ActionResult Index()
        {
            return View(db.QuizLibrary.ToList());
        }
        // GET: Library/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuizLibrary quizLibrary = db.QuizLibrary.Find(id);
            if (quizLibrary == null)
            {
                return HttpNotFound();
            }
            return View(quizLibrary);
        }
        // GET: Library/Create
        public ActionResult Create()
        {
            ViewBag.sorular = db.Question.ToList();
            return View();
        }
        // POST: Library/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Questions,MailSend,StartDate,EndDate,CreatedDate,Comment")] QuizLibrary quizLibrary, string[] Question)
        {
            if (ModelState.IsValid)
            {
                quizLibrary.Questions = string.Join("|", Question);
                quizLibrary.CreatedDate = DateTime.Now.ToString();
                db.QuizLibrary.Add(quizLibrary);
                db.SaveChanges();
                Logger.LogKeeper(quizLibrary.Name + " Kütüphane oluşturdu");
                return RedirectToAction("Index");
            }
            return View(quizLibrary);
        }
        // GET: Library/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuizLibrary quizLibrary = db.QuizLibrary.Find(id);
            quizLibrary.Question = quizLibrary.Questions.Split('|').ToArray();
            ViewBag.sorular = db.Question.ToList();
            if (quizLibrary == null)
            {
                return HttpNotFound();
            }
            return View(quizLibrary);
        }
        // POST: Library/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Questions,MailSend,StartDate,EndDate,CreatedDate,Comment")] QuizLibrary quizLibrary, string[] Question)
        {
            if (ModelState.IsValid)
            {
                quizLibrary.Questions = string.Join("|", Question);
                db.Entry(quizLibrary).State = EntityState.Modified;
                db.SaveChanges();
                Logger.LogKeeper(quizLibrary.Name + " adlı Kütüphaneyi Güncelledi");
                return RedirectToAction("Index");
            }
            return View(quizLibrary);
        }
        // GET: Library/Delete/5
        // POST: Library/Delete/5
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuizLibrary quizLibrary = db.QuizLibrary.Find(id);
            db.QuizLibrary.Remove(quizLibrary);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuestionApp/Views/Library/Create.cshtml
@model QuestionApp.Models.QuizLibrary
@{
    ViewBag.Title = "From list";
}
@using (Html.BeginForm("Create", "Library", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12 col-xlg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Questions, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.ListBoxFor(model => model.Question, new SelectList(ViewBag.sorular, "ID", "Questions"), new { @class = "form-control", @id = "kulls" })
                            @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
                        </div>
                    </div>
                   
                    <div class="form-group">
                        @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn btn-outline-primary" name="Kaydet" value="Ekle" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<link href="~/Content/toastr.min.css" rel="stylesheet" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/toastr.min.js"></script>
    <link href="~/Content/multi-select.css" rel="stylesheet" />
    <script src="~/Content/jquery.multi-select.js"></script>
    <script src="~/Scripts/Searchq.js"></script>
    <script type="text/javascript">
        // run pre selected options
        $('#kulls').multiSelect({
            selectableHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Kullanıcı ara'>",
            selectionHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Seçilmiş olanı ara'>",
            afterInit: function (ms) {
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';
                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                    .on('keydown', function (e) {
                        if (e.which === 40) {
                            that.$selectableUl.focus();
                            return false;
                        }
                    });
                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                    .on('keydown', function (e) {
                        if (e.which == 40) {
                            that.$selectionUl.focus();
                            return false;
                        }
                    });
            },
            afterSelect: function () {
                this.qs1.cache();
                this.qs2.cache();
            },
            afterDeselect: function () {
                this.qs1.cache();
                this.qs2.cache();
            }
        });
    </script>
    @if (TempData["hata"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["success"]("Kayıt Düzenlendi")
                toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
    @if (TempData["getir"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["success"]("Kayıt Getirildi")
                toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
}

QuestionApp/Views/Library/Delete.cshtml
@model QuestionApp.Models.QuizLibrary
@{
    ViewBag.Title = "Delete";
}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QuizLibrary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Questions)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Questions)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MailSend)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MailSend)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuestionApp/Views/Library/Details.cshtml
@model QuestionApp.Models.QuizLibrary
@{
    ViewBag.Title = "Details";
}
<style>
    input {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        width: 200px;
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }

    input {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        width: 200px;
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }

        input:focus {
            outline: none;
            border-color: #aaa
        }

    select {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }

    select {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }

        select:focus {
            outline: none;
            border-color: #aaa
        }
</style>

<div class="row">
    <div class="col-lg-12 col-xlg-12 col-md-12">
        <div class="card">
            <div class="card-body">
                <p>
                    @Html.ActionLink("< Listeye Geri Dön", "Index")
                </p>
                <p style="float:right">
                    @Html.ActionLink("Düzenle", "Edit", new { id = Model.ID }, new { @class = "btn btn-outline-primary" })
                    <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModal">
                        Sil
                    </button>
                </p>
               
                <p>
                    <h4>Soru Kütüphanesi</h4>
                </p>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.MailSend)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.MailSend)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.StartDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.StartDate)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.EndDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.EndDate)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedDate)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Questions)
                    </dt>
                    <dd id="list">
                        <div id="hacker-list">
                           
                            <ul class="ul list">
                                @{
                                    QuestionApp.Models.DBContext db = new QuestionApp.Models.DBContext();
                                    foreach (var item in Model.Questions.Split('|').ToArray())
                                    {
                                        if (item != null)
                                        {
                                            int ID = Convert.ToInt32(item);

                                            var bul = db.Question.FirstOrDefault(x => x.ID == ID);
                                            if (bul != null)
                                            {
                                                <li><a href="~/licence/details/@bul.ID" class="name">@bul.Questions</a></li>
                                            }

                                        }
                                    }
                                }
                            </ul>
                        </div>
                    </dd>
                </dl>
                <p>      
                    @Html.ActionLink("< Listeye Geri Dön", "Index")
                </p>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>   
}
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Kaydı silmek istediğinize emin misiniz ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @Model.Name adlı kaydı silmek istediğinize emin misiniz ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hayır</button>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Evet" class="btn btn-danger" />
                }
            </div>
        </div>
    </div>
</div>

QuestionApp/Views/Library/Edit.cshtml
@model QuestionApp.Models.QuizLibrary
@{
    ViewBag.Title = "Düzenle";
}
@using (Html.BeginForm("Edit", "Library", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12 col-xlg-12 col-md-12">
            <div class="card">
          
                <div class="card-body">
                    <p>
                        @Html.ActionLink("< Listeye Geri Dön", "Index")
                    </p>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Questions, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.ListBoxFor(model => model.Question, new SelectList(ViewBag.sorular, "ID", "Questions"), new { @class = "form-control", @id = "kulls" })
                            @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
                        </div>
                    </div>
                  
                    <div class="form-group">
                        @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn btn-outline-primary" name="Güncelle" value="Ekle" />
                        </div>
                    </div>
                    <p>
                    <p>
                        @Html.ActionLink("< Listeye Geri Dön", "Index")
                    </p>
                    </p>
                </div>
            </div>
        </div>
    </div>
}
<link href="~/Content/toastr.min.css" rel="stylesheet" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/toastr.min.js"></script>
    <link href="~/Content/multi-select.css" rel="stylesheet" />
    <script src="~/Content/jquery.multi-select.js"></script>
    <script src="~/Scripts/Searchq.js"></script>
    <script type="text/javascript">
        // run pre selected options
        $('#kulls').multiSelect({
            selectableHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Kullanıcı ara'>",
            selectionHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Seçilmiş olanı ara'>",
            afterInit: function (ms) {
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';
                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                    .on('keydown', function (e) {
                        if (e.which === 40) {
                            that.$selectableUl.focus();
                            return false;
                        }
                    });
                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                    .on('keydown', function (e) {
                        if (e.which == 40) {
                            that.$selectionUl.focus();
                            return false;
                        }
                    });
            },
            afterSelect: function () {
                this.qs1.cache();
                this.qs2.cache();
            },
            afterDeselect: function () {
                this.qs1.cache();
                this.qs2.cache();
            }
        });
    </script>
    @if (TempData["hata"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["success"]("Kayıt Düzenlendi")
                toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
    @if (TempData["getir"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["success"]("Kayıt Getirildi")
                toastr.options = {
                    "closeButton": false,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
}

QuestionApp/Views/Library/Index.cshtml
@model IEnumerable<QuestionApp.Models.QuizLibrary>
@{
    ViewBag.Title = "Kütüphane";
}
<style>
    td {
        white-space: nowrap;
        overflow: hidden;
        -o-text-overflow: ellipsis;
        -ms-text-overflow: ellipsis;
        text-overflow: ellipsis;
        max-width: 200px;
    }
    input {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        width: 200px;
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }
    input {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        width: 200px;
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }
        input:focus {
            outline: none;
            border-color: #aaa
        }
    select {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }
    select {
        border-radius: 25px;
        padding: 7px 14px;
        background-color: transparent;
        border: solid 1px rgba(0, 0, 0, 0.2);
        box-sizing: border-box;
        color: #2e2e2e;
        margin-bottom: 5px
    }
        select:focus {
            outline: none;
            border-color: #aaa
        }
</style>
<div class="row">
    <div class="col-12 col-md-12">
        <div class="card">
            <div class="card-body">
                <table id="datatable" class="table tables table-hover table-sm " style="width: 100%;" role="grid" aria-describedby="scroll_ver_dynamic_hei_info">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                           
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                          
                            <td>
                                <a href="/Library/Details/@item.ID" data-toggle="tooltip" data-placement="top" title="" data-original-title="Detaylar"><i class="fa fa-eye color-muted m-r-5"></i> </a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<link href="~/Content/toastr.min.css" rel="stylesheet" />
<link href="~/Content/jquery.dataTables.css" rel="stylesheet" />
@section Scripts {
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/jquery.canvasjs.min.js"></script>
    <script src="~/Scripts/canvasjs.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
    @Scripts.Render("~/bundles/Datatable")
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable({
                "language": {
                    "url": "/Scripts/Turkish.json"
                },
                "dom": ' <"search"f><"bottom"l>rt<"bottom"ip><"clear"><"top"B>',
                buttons: [
                    {
                        extend: 'excelHtml5',
                        exportOptions:
                        {
                            columns: [0, 1, 2],
                        },
                        text: '<i class="fa fa-file-excel-o"></i>',
                        titleAttr: 'Excel',
                        className: 'btn btn-outline-secondary'
                    },
                    {
                        extend: 'pdfHtml5',
                        pageSize: 'LEGAL',
                        exportOptions:
                        {
                            columns: [0, 1, 2],
                        },
                        text: '<i class="fa fa-file-pdf-o"></i>',
                        titleAttr: 'PDF',
                        className: 'btn btn-outline-secondary'
                    },
                    {
                        text: '<b>Kütüphane Ekle</b>',
                        action: function (e, dt, button, config) {
                            window.location = '/Library/Create';
                        },
                        className: 'btn btn-outline-info'
                    },
                ]
            });
        });
    </script>
    @if (TempData["Message"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["success"]("Kayıt Silindi", "Kayıt Silindi")
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
    @if (TempData["Error"] != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                Command: toastr["error"]("Hata Oluştu", "Hata Oluştu")
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": false,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            })
        </script>
    }
}